=== jasbir-s-minhas/spring-hibernate/spring-mvc-demo/src/main/resources/capability.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Note: hand-coded XSD. Please do not generate this file with a tool.
 * @author Jasbir Minhas
 * @version 1.0
 * @since 2017-11-07
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
	<xs:element name="capabilityConfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="capabilityGroup" type="CapabilityGroupType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
        <xs:unique name="uniqueCapabilityGroup">
            <xs:selector xpath=".//capabilityGroup"/>
            <xs:field xpath="@name"/>
        </xs:unique>
        <xs:unique name="uniqueCapability">
            <xs:selector xpath=".//capability"/>
            <xs:field xpath="@name"/>
        </xs:unique>
	</xs:element>

	<!-- CapabilityGroupType definition -->
	<xs:complexType name="CapabilityGroupType">
		<xs:sequence>
            <xs:element name="enabled" minOccurs="1" maxOccurs="13">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:token" >
                            <xs:attribute name="code" type="ProvCodeEnumType" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
			<xs:element name="capabilityGroup" type="CapabilityGroupType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="capability" type="CapabilityType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:token" use="required"/>
		<!--<xs:attribute name="enabled" type="xs:boolean" use="required"/>-->
	</xs:complexType>

    <!-- CapabilityType definition -->
	<xs:complexType name="CapabilityType">
		<xs:sequence>
			<xs:element name="value" minOccurs="1" maxOccurs="13">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:token" >
                            <xs:attribute name="code" type="ProvCodeEnumType" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
		</xs:sequence>
        <xs:attribute name="name" type="xs:token" use="required"/>
        <xs:attribute name="type" type="CapabilityAttribType" use="required"/>
	</xs:complexType>

    <!-- CapabilityAttribType definition -->
    <xs:simpleType name="CapabilityAttribType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="string"/>
            <xs:enumeration value="double"/>
            <xs:enumeration value="long"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- valueType definition -->
	<xs:complexType name="ValueType">
		<xs:simpleContent>
			<xs:extension base="xs:token">
				<xs:attribute name="type" type="xs:token" use="required"/>
				<!--<xs:assert test="if (@type='boolean')  then . castable as xs:boolean-->
                        <!--else if (@type='double')     then . castable as xs:double-->
                        <!--else if (@type='long')       then . castable as xs:long-->
                        <!--else if (@type='string')    then . castable as xs:token-->
                        <!--else false()"/>-->
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

    <!--Uncomment the following province codes as more provinces are implemented in Delta -->
	<xs:simpleType name="ProvCodeEnumType" >
		<xs:restriction base="xs:token">
            <!--<xs:enumeration value="AB"/>-->
            <!--<xs:enumeration value="BC"/>-->
            <!--<xs:enumeration value="MB"/>-->
            <xs:enumeration value="NB"/>
            <!--<xs:enumeration value="NL"/>-->
            <xs:enumeration value="NS"/>
            <!--<xs:enumeration value="NT"/>-->
            <!--<xs:enumeration value="NU"/>-->
            <xs:enumeration value="ON"/>
            <!--<xs:enumeration value="PE"/>-->
            <!--<xs:enumeration value="QC"/>-->
            <!--<xs:enumeration value="SK"/>-->
            <!--<xs:enumeration value="YT"/>-->
        </xs:restriction>
	</xs:simpleType>
</xs:schema>

=== jasbir-s-minhas/spring-hibernate/spring-mvc-demo/src/main/resources/capability.xml
<?xml version="1.0" encoding="UTF-8"?>
<capabilityConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="capability.xsd">
    <!-- A test group for testing the capability framework. Meant to be used for testing and an example only. -->
    <capabilityGroup name="testGroup1L1">
        <enabled code="NS">true</enabled>
        <enabled code="NB">true</enabled>
        <enabled code="ON">true</enabled>
        <capabilityGroup name="testGroup1L2">
            <enabled code="NS">false</enabled>
            <enabled code="NB">true</enabled>
            <enabled code="ON">true</enabled>
            <capability name="testStringCapability" type="string">
                <value code="NS">NS-String</value>
                <value code="NB">NB-String</value>
                <value code="ON">ON-String</value>
                <value code="NB">Test</value>
            </capability>
            <capability name="testBooleanCapability" type="boolean">
                <value code="NS">true</value>
                <value code="NB">false</value>
                <value code="ON">true</value>
            </capability>
            <capability name="testLongCapability" type="long">
                <value code="NS">100</value>
                <value code="NB">200</value>
                <value code="ON">999</value>
            </capability>
            <capability name="testDoubleCapability" type="boolean">
                <value code="NS">1.5</value>
                <value code="NB">2.5</value>
                <value code="ON">10.9</value>
            </capability>
        </capabilityGroup>
    </capabilityGroup>
    <capabilityGroup name="testGroup1L2-">
        <enabled code="ON">true</enabled>
        <capability name="testStringCapability3" type="string">
            <value code="NS">NS-String</value>
            <value code="NB">NB-String</value>
            <value code="ON">On-String</value>
            <value code="NB">Test</value>
        </capability>
    </capabilityGroup>
    <!--eHealth Capability Group-->
    <capabilityGroup name="eHealth">
        <enabled code="NS">true</enabled>
        <enabled code="NB">true</enabled>
        <enabled code="ON">true</enabled>
        <!--View ADR Status-->
        <capability type="boolean" name="adrStatus">
            <value code="NS">false</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--View replaced version status Changes for Allergy/Intolerance-->
        <capability type="boolean" name="allergyReplacedVersion">
            <value code="NS">true</value>
            <value code="NB">true</value>
            <value code="ON">false</value>
        </capability>
        <!--Allergy Status Drop Down Option-->
        <capability type="boolean" name="allergyStatus">
            <value code="NS">true</value>
            <value code="NB">true</value>
            <value code="ON">false</value>
        </capability>
        <!--Sub E-health configurable capability to check whether DIN exists for the entered chemical or not-->
        <capability type="boolean" name="chemicalDINCheck">
            <value code="NS">true</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--There is a sub-ehealth configurable capability mode in HW (On/Off)  for the comprehensive profile to
        be user selectable or mandatory.-->
        <capability type="boolean" name="comprehensiveModifier">
            <value code="NS">true</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--View replaced version status Changes for medical condition-->
        <capability type="boolean" name="conditionReplacedVersion">
            <value code="NS">true</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--DECN Business entity type value-->
        <capability type="boolean" name="decnBusinessEntityType">
            <value code="NS">true</value>
            <value code="NB">true</value>
            <value code="ON">false</value>
        </capability>
        <!--TODO: Add comments.-->
        <capability type="boolean" name="displayManagementHistoryAtCv">
            <value code="NS">true</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--TODO: Add comments.-->
        <capability type="boolean" name="displayProvincialData">
            <value code="NS">true</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--There is a sub-ehealth configurable capability mode in HW (On/Off)  for the Tx of selected Provincial
        Rx on Rx Table to be user viewable or not.-->
        <capability type="boolean" name="displayTxForProvincialRx">
            <value code="NS">false</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--TODO: Add comments.-->
        <capability type="boolean" name="eligibleForTrial">
            <value code="NS">true</value>
            <value code="NB">true</value>
            <value code="ON">false</value>
        </capability>
        <!--ePrescribing Enabled Check-->
        <capability type="boolean" name="ePrescribing">
            <value code="NS">true</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--There is a sub-ehealth configurable capability mode in HW (On/Off) to enable importing
        provincial prescriptions.-->
        <capability type="boolean" name="importProvincialPrescriptions">
            <value code="NS">true</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--Intolerance Status Dropdown Option-->
        <capability type="boolean" name="intolStatus">
            <value code="NS">true</value>
            <value code="NB">true</value>
            <value code="ON">true</value>
        </capability>
        <!--Link to Provincial Rx-->
        <capability type="boolean" name="linkProvincialRx">
            <value code="NS">true</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--Enable Link to Prov Indicator-->
        <capability type="boolean" name="linkStatusIndicator">
            <value code="NS">true</value>
            <value code="NB">true</value>
            <value code="ON">false</value>
        </capability>
        <!--Provincial Location Search Enabled Check-->
        <capability type="boolean" name="locationSearch">
            <value code="NS">true</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--Manage Consent Enabled Check-->
        <capability type="boolean" name="manageConsent">
            <value code="NS">true</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--Provincial Patient Linking Is Required Or Not-->
        <capability type="boolean" name="patientLinkage">
            <value code="NS">true</value>
            <value code="NB">true</value>
            <value code="ON">false</value>
        </capability>
        <!--There is a sub-ehealth configurable capability mode in HW (On/Off) to make the patient profile review
        mandatory during CV.-->
        <capability type="boolean" name="patientProRevIsMandatoryAtCV">
            <value code="NS">false</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--Enable Provincial Patient Search On Client Registry-->
        <capability type="boolean" name="patientSearch">
            <value code="NS">true</value>
            <value code="NB">true</value>
            <value code="ON">false</value>
        </capability>
        <!--TODO: Add comments.-->
        <capability type="boolean" name="phoneEnabled">
            <value code="NS">false</value>
            <value code="NB">true</value>
            <value code="ON">false</value>
        </capability>
        <!--TODO: Add comments.-->
        <capability type="boolean" name="postalCodeEnabled">
            <value code="NS">false</value>
            <value code="NB">true</value>
            <value code="ON">false</value>
        </capability>
        <!--Rx Order Id Enabled Check-->
        <capability type="boolean" name="printRxOrderId">
            <value code="NS">false</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--There must be a sub-ehealth configuration capability (ON/OFF) in HW to allow the system to execute the
         Producer ID check when linking provincial patient to local.-->
        <capability type="boolean" name="producerIDCheck">
            <value code="NS">true</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--Provincial Provider Search Enabled Check-->
        <capability type="boolean" name="providerSearch">
            <value code="NS">true</value>
            <value code="NB">false</value>
            <value code="ON">false</value>
        </capability>
        <!--Non-Fill Actions on Provincial Rx require Intake Enabled-->
        <capability type="boolean" name="provincialRxRequireIntake">
            <value code="NS">true</value>
            <value code="NB">true</value>
            <value code="ON">false</value>
        </capability>
        <!--There is a sub-ehealth configurable capability mode in HW (On/Off)  for the medication profile
